In [1]:
import torch
import numpy as np
import torch.nn.functional as F
from deeprobust.graph.utils import *
from deeprobust.graph.data import Dataset
import argparse

In [2]:
data = Dataset(root='/home/zmm/advUnno/dataset/raw', name='citeseer', setting='nettack')
adj, features, labels = data.adj, data.features, data.labels
idx_train, idx_val, idx_test = data.idx_train, data.idx_val, data.idx_test
idx_train = torch.LongTensor(idx_train)
idx_val = torch.LongTensor(idx_val)
idx_test = torch.LongTensor(idx_test)
features = torch.FloatTensor(np.array(features.todense()))
labels = torch.LongTensor(labels)

Loading citeseer dataset...
Selecting 1 largest connected components


In [3]:
print(idx_train.shape, idx_val.shape, idx_test.shape)
print(labels)

torch.Size([210]) torch.Size([211]) torch.Size([1688])
tensor([1, 4, 4,  ..., 3, 1, 1])


In [4]:
adj, features, labels

(<2110x2110 sparse matrix of type '<class 'numpy.float32'>'
 	with 7336 stored elements in Compressed Sparse Row format>,
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 tensor([1, 4, 4,  ..., 3, 1, 1]))

In [5]:
# 划分target
import random
seed = 19
np.random.seed(seed)
target_sets = []
for _ in range(5):
    target_sets.append(np.random.choice(idx_test.numpy(), 50, replace=False))
print(target_sets)

[array([ 681,  529,  250, 1177,  423,  893,  254,  955,  751, 1124,  600,
        329, 1500,  332,  221,  522, 1827,  304,  963,  753,  587,  141,
        945,  462, 1463,  635, 2010, 1926, 1693,  854,  628,  158, 1744,
        849,  917,  836,  838,  276,  958, 2077, 1856,    2,  151,  526,
        368,  317,  178,  614,   59,  876]), array([1264, 1759, 1983,   83, 1327, 1535,  747,  487, 1208,  484, 1564,
       1485, 1905,  648, 1770,  858, 1465,  400, 1359, 1769, 1661,  358,
        585, 1004, 1671, 1201, 1020,  256,  963,  802, 1708, 1756, 1073,
        111, 1679, 1795,  903, 1178,  601, 1361,  548,  212, 1156,  634,
       1450, 1261, 1384,  777,  418,  529]), array([1270,  123,  612, 1022, 2050, 1845,  898, 1555,  855,    4,  795,
        283,  307, 1703,  658, 1244,  415,  428, 1503, 1079, 1694, 1808,
       1141,  842,   19, 1077, 2048, 1217,  783,  164, 1578,  959,  603,
       1299,  124,  958, 1742,  613,  442,  805,  121,  858, 1816, 1050,
        305,  240, 1971, 1056,  2

In [6]:
'''
adj:对称，无自环，未归一化
features：未归一化
idx_train, idx_val, idx_test：0.1/0.1/0.8
sens：contry信息
'''
import pickle as pkl
with open('/home/zmm/advUnno/dataset/citeseer.pkl','wb') as f:
    pkl.dump([adj, features, labels, idx_train, idx_val, idx_test, target_sets, []],f)